version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-pong
    restart: always
    command: --event_scheduler=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pong
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./pong.sql:/docker-entrypoint-initdb.d/pong.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-pong
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql-data: